name: section 3 action 2 - node
on: push
jobs:
  validate_code:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository to runner
        uses: actions/checkout@v4
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test