name: section 3 action 2 - node
on: [push, workflow_dispatch]
jobs:
  validate_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: install dependencies
        run: npm i
      - name: run tests
        run: npm test
  deploy:
    needs: validate_code
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: install dependencies
        run: npm i
      - name: build project
        run: npm run build
      - name: deploy
        run: echo "deploying"